version: '3.8'
services:
  app.gateway:
    # build:
      # dockerfile: ./gateway/Dockerfile.dev
    environment: 
      - WEB_APP_PORT=4200 # webpack server hot reload
  app.api:
    build:
      target: dev
    environment: 
      - LOG_LEVEL=1       
      - OPCUA_MODE=0
      - ASPNETCORE_ENVIRONMENT=Development
      - RESET_DATABASE=true
    
  app.ui:
    build:
      dockerfile: ./HMI.UI/Dockerfile.dev
    ports:
      - '4200:4200'
    volumes: # For webpack dev server to use our local files
      - ./HMI.UI/src:/app/src
    environment: 
      - NODE_ENV=development